server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root

logging:
  level:
    org.springframework.web: ERROR
    ma.pfe: DEBUG